version: '3'

services:
  app:
    image: amazoncorretto:17
    volumes:
      - ./:/app
    ports:
      - 8080:8080
    tty: true
    environment:
      - USE_SSL=false
      - AWS_ACCESS_KEY_ID=dummy
      - AWS_SECRET_ACCESS_KEY=dummy
      - AWS_DEFAULT_REGION=ap-northeast-1
    command:
      - /bin/bash
  localstack:
    image: localstack/localstack:latest
    environment:
      - SERVICES=s3,sqs
      - DEFAULT_REGION=ap-northeast-1
      - DATA_DIR=/tmp/localstack/data
    volumes:
      - ./localstack:/tmp/localstack
    ports:
      - 4566:4566
